## Tarefa Aprendizagem não supervisionada

Anderson rosa cascalho - Trilha 04

## Importando as bibliotecas e base

In [ ]:
import numpy as np
from sklearn.decomposition import PCA
import pandas as pd
import matplotlib.pyplot as plt

from google.colab import files
uploaded = files.upload()

Saving APR NÃO SUP_Tarefa_Trilha 4.xlsx to APR NÃO SUP_Tarefa_Trilha 4 (13).xlsx


In [ ]:
# importando io para carregar o arquivo
import io


#comando para importar arquivo CSV: read_csv e salvar os dados 
dataFrame = pd.read_excel(io.BytesIO(uploaded['APR NÃO SUP_Tarefa_Trilha 4.xlsx']))
dataFrame.head()

GRANDE_REG  ...       DATA
0  Centro-Oeste  ... 1998-02-19
1  Centro-Oeste  ... 1998-02-19
2  Centro-Oeste  ... 1998-02-19
3  Centro-Oeste  ... 1998-02-19
4  Centro-Oeste  ... 1998-02-19

[5 rows x 12 columns]

## Analise exploratoria dos dados e pré-processamento


In [ ]:
dataFrame.describe()

COD_UF          COD       COD_MUN
count  1420.000000  1420.000000  1.420000e+03
mean     34.454930  3449.743662  3.459478e+06
std       8.909937   891.706631  8.920921e+05
min      11.000000  1101.000000  1.100205e+06
25%      27.000000  2701.000000  2.701283e+06
50%      35.000000  3506.000000  3.537354e+06
75%      42.000000  4204.000000  4.204768e+06
max      53.000000  5301.000000  5.300108e+06

In [ ]:
dataFrame.shape

(1420, 12)

In [ ]:
dataFrame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1420 entries, 0 to 1419
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype         
---  ------         --------------  -----         
 0   GRANDE_REG     1420 non-null   object        
 1   COD_UF         1420 non-null   int64         
 2   SIGLA_UF       1420 non-null   object        
 3   COD            1420 non-null   int64         
 4   NOME           1420 non-null   object        
 5   TIPO           1420 non-null   object        
 6   COD_CAT_ASSOC  1420 non-null   object        
 7   CAT_ASSOC      1420 non-null   object        
 8   COD_MUN        1420 non-null   int64         
 9   NOME_MUN       1420 non-null   object        
 10  LEG            1420 non-null   object        
 11  DATA           1420 non-null   datetime64[ns]
dtypes: datetime64[ns](1), int64(3), object(8)
memory usage: 133.2+ KB


In [ ]:
# Remove as linhas duplicadas e NaN
dataFrame = dataFrame.drop_duplicates()
dataFrame = dataFrame.dropna()
del dataFrame['DATA']
dataFrame.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1420 entries, 0 to 1419
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   GRANDE_REG     1420 non-null   object
 1   COD_UF         1420 non-null   int64 
 2   SIGLA_UF       1420 non-null   object
 3   COD            1420 non-null   int64 
 4   NOME           1420 non-null   object
 5   TIPO           1420 non-null   object
 6   COD_CAT_ASSOC  1420 non-null   object
 7   CAT_ASSOC      1420 non-null   object
 8   COD_MUN        1420 non-null   int64 
 9   NOME_MUN       1420 non-null   object
 10  LEG            1420 non-null   object
dtypes: int64(3), object(8)
memory usage: 133.1+ KB


In [ ]:
import plotly.express as px;

fig  = px.scatter(dataFrame, x = 'COD_UF', y = 'COD', log_x = True, width = 800)
fig.update_traces(marker = dict(size = 12, line=dict(width = 2)), selector = dict(mode = 'markers'))
fig.update_layout(title = 'Regiões Metropolitanas')
fig.update_xaxes(title = 'Log(Grandes regiões)')
fig.update_yaxes(title = 'UF')
fig.show()

# Encoding valores categóricos

In [ ]:
def getDummies(column):
  return pd.get_dummies(dataFrame, columns=[column])

In [ ]:
dataFrame = getDummies('GRANDE_REG')
dataFrame = getDummies('SIGLA_UF')
dataFrame = getDummies('NOME')
dataFrame = getDummies('TIPO')
dataFrame = getDummies('CAT_ASSOC')
dataFrame = getDummies('COD_CAT_ASSOC')
dataFrame = getDummies('NOME_MUN')
dataFrame = getDummies('LEG')
dataFrame.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1420 entries, 0 to 1419
Columns: 1782 entries, COD_UF to LEG_inclusão de município - Lei Complementar  78 de 25.03.2010
dtypes: int64(3), uint8(1779)
memory usage: 2.5 MB


In [ ]:
dataFrame.head()

COD_UF  ...  LEG_inclusão de município - Lei Complementar  78 de 25.03.2010
0      53  ...                                                  0             
1      52  ...                                                  0             
2      52  ...                                                  0             
3      52  ...                                                  0             
4      52  ...                                                  0             

[5 rows x 1782 columns]

Padronizando os valores

In [ ]:
X= dataFrame.values
X

array([[     53,    5301, 5300108, ...,       0,       0,       0],
       [     52,    5202, 5200100, ...,       0,       0,       0],
       [     52,    5202, 5200175, ...,       0,       0,       0],
       ...,
       [     42,    4202, 4207502, ...,       0,       0,       0],
       [     42,    4202, 4213203, ...,       0,       0,       0],
       [     42,    4202, 4218202, ...,       0,       0,       0]])

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X)
X_scaler = scaler.transform(X)
X_scaler

array([[ 2.08212519,  2.07681368,  2.06400012, ..., -0.09231862,
        -0.03755579, -0.05944383],
       [ 1.96985141,  1.96575151,  1.95185561, ..., -0.09231862,
        -0.03755579, -0.05944383],
       [ 1.96985141,  1.96575151,  1.95193972, ..., -0.09231862,
        -0.03755579, -0.05944383],
       ...,
       [ 0.84711359,  0.84391136,  0.83880051, ..., -0.09231862,
        -0.03755579, -0.05944383],
       [ 0.84711359,  0.84391136,  0.84519336, ..., -0.09231862,
        -0.03755579, -0.05944383],
       [ 0.84711359,  0.84391136,  0.85079901, ..., -0.09231862,
        -0.03755579, -0.05944383]])

## Selecione duas técnicas de redução dentre as que foram estudadas nas trilhas 3 e 4 (uma linear e uma não linear). 

Tecnica linear: PCA (Principal Component Analysis)

---

Tecnica não linear: LLE (Locally Linear Embedding)


## Aplique as técnicas, utilizando a biblioteca scikit learn, e analise qual delas teve o melhor desempenho nesta base. 

Aplicação tecnica linear

In [ ]:
X

array([[     53,    5301, 5300108, ...,       0,       0,       0],
       [     52,    5202, 5200100, ...,       0,       0,       0],
       [     52,    5202, 5200175, ...,       0,       0,       0],
       ...,
       [     42,    4202, 4207502, ...,       0,       0,       0],
       [     42,    4202, 4213203, ...,       0,       0,       0],
       [     42,    4202, 4218202, ...,       0,       0,       0]])

In [ ]:
pca = PCA(random_state=2020)
pca.fit(X)
X_pca = pca.transform(X_scaler)
print("Variância explicada para todos os componentes =", sum(pca.explained_variance_ratio_ * 100))

TypeError: ignored

In [ ]:
import matplotlib.pyplot as plt 

plt.plot(np.cumsum(pca.explained_variance_ratio_))
plt.xlabel('Número do componente')
plt.ylabel('Variância explicada')

In [ ]:
pca2Components = PCA(n_components=2, random_state=2020)
pca2Components.fit(X)
X_pca2Components = pca2Components.transform(X_scaler)
valor = sum(pca2Components.explained_variance_ratio_ * 100)
print("Variância explicada para 2 componentes: ", valor)

In [ ]:
plt.plot(np.cumsum(pca2Components.explained_variance_ratio_))
plt.xlabel('Número do componente')
plt.ylabel('Variância explicada')

## Aplicação tecnica não linear

Exemplo 1

In [ ]:
import matplotlib.pyplot as plt

# This import is needed to modify the way figure behaves
from mpl_toolkits.mplot3d import Axes3D
Axes3D

# ----------------------------------------------------------------------
# Locally linear embedding of the swiss roll

from sklearn import manifold, datasets
A, color = datasets.make_swiss_roll(n_samples=len(X_scaler))
X = X_scaler

print("Computing LLE embedding")
X_r, err = manifold.locally_linear_embedding(X_scaler, n_neighbors=12, n_components=2)
print("Done. Reconstruction error: %g" % err)

# ----------------------------------------------------------------------
# Plot result
fig = plt.figure()

ax = fig.add_subplot(211, projection='3d')
ax.scatter(X[:, 0], X[:, 1], X[:, 2], c=color, cmap=plt.cm.Spectral)

ax.set_title("Original data")
ax = fig.add_subplot(212)
ax.scatter(X_r[:, 0], X_r[:, 1], c=color, cmap=plt.cm.Spectral)
plt.axis('tight')
plt.xticks([]), plt.yticks([])
plt.title('Projected data')
plt.show()

Exemplo 2

In [ ]:
#Importing the required libraries
from collections import OrderedDict
from functools import partial
from time import time
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.ticker import NullFormatter
from sklearn import manifold, datasets
from sklearn.decomposition import PCA

#This import is needed to silence pyflakes
Axes3D
#Then we load the swiss roll dataset
n_points = len(X_scaler)
A, color = datasets.make_swiss_roll(n_points, random_state=0)
X = X_scaler
n_neighbors = 12
n_components = 2
# Creating the plot
fig = plt.figure(figsize=(15, 8))
fig.suptitle("Manifold Learning with %i points, %i neighbors"
             % (len(X_scaler), n_neighbors), fontsize=14)
# Adding 3d scatter plot
ax = fig.add_subplot(231, projection='3d')
ax.scatter(X[:, 0], X[:, 1], X[:, 2], c=color, cmap=plt.cm.Spectral)
ax.view_init(4, -72)
# Making a dictionary 'methods' containing LLE, t-SNE and PCA
LLE = partial(manifold.LocallyLinearEmbedding, n_neighbors, n_components, eigen_solver='auto')
methods = OrderedDict()
methods['LLE'] = LLE(method='standard')
# Plotting the results
for i, (label, method) in enumerate(methods.items()):
    t0 = time()
    Y = method.fit_transform(X)
    t1 = time()
    print("%s: %.2g sec" % (label, t1 - t0))
    ax = fig.add_subplot(2, 3, 2 + i+(i>1))
    ax.scatter(Y[:, 0], Y[:, 1], c=color, cmap=plt.cm.Spectral)
    ax.set_title("%s (%.2g sec)" % (label, t1 - t0))
    ax.xaxis.set_major_formatter(NullFormatter())
    ax.yaxis.set_major_formatter(NullFormatter())
    ax.axis('tight')
plt.show()

## Apresente os resultados e descreva o desempenho das técnicas 

Na avaliação do codigo acima podemos identificar que o dataset possui uma estrutura linear de dado, pois conseguimos identificar uma aderencia de 99.99999997% do modelo PCA. Não consegui identificar, ou melhor dizendo, eu não saberia como explicar qual modelo foi melhor, mas se fossemos levar em consideração o tempo de processamento, o PCA ganha, LLE levou cerca de 9s para gerar a imagem com 2 dimensões, já o PCA uma pouco mais de 3s